### PR TITLE
Main pose2

### PR DESCRIPTION
**Pull request by SurajKRB**
Ladies,

I have added app icon and change the name of our app.

I did cleaning of some code, specially, settings from camera prerviews

I also tested our own model. and seems like we might have to train more. But we can do that later. It's all about now collecting good training material.

### CODE REVIEW

**Comment by giaongo** [comment]
Is this PR open for reviewing or still in progress?

**Comment by SurajKRB** [comment]
It is open to review. I have stopped working till monday

**Comment by giaongo** [comment]
You forgot to request reviewers :))

**Comment by SurajKRB** [comment]
Did I, Hmm, How does it look now?

**Comment by giaongo** [comment]
I am just checking what you have changed. I may continue my work on your branch and share the same PR

**Review by Shilupa — APPROVED** [review]
Looks fine.

**Review by chinguyen202 — APPROVED** [review]

**Review by giaongo — APPROVED** [review]
All changes from this branch are ready for merge. Could you please check my changes out @SurajKRB and let me know if they are all okay before merging to main ? Thanks

**Pull request merged**
